export default Object.freeze({
    USER_AVAILABILITY_DATA: 'USER_AVAILABILITY_DATA',
    RESET_USERNAME_DATA: 'RESET_USERNAME_DATA',
    EMAIL_AVAILABILITY_DATA: 'EMAIL_AVAILABILITY_DATA',
    RESET_EMAIL_DATA: 'RESET_EMAIL_DATA',
    PASSWORD_AVAILABILITY: 'PASSWORD_AVAILABILITY',
    RESET_PASSWORD_DATA: 'RESET_PASSWORD_DATA',
    RESET_REGISTER_FORM: 'RESET_REGISTER_FORM'
});
