export default Object.freeze({
    PRIROTY_STATUS: 'PRIROTY_STATUS',
    UPDATE_PRIORITY_CHECKBOX: 'UPDATE_PRIORITY_CHECKBOX',
    REMOVE_PRIORITY: 'REMOVE_PRIORITY',
    ADD_PRIORITY: 'ADD_PRIORITY',
    ALL_PRIROTY_STATUS: "ALL_PRIROTY_STATUS"
});
