export default Object.freeze({
    PRIROTY_STATUS: 'PRIROTY_STATUS',
    UPDATE_PRIORITY_CHECKBOX: 'UPDATE_PRIORITY_CHECKBOX',
    REMOVE_PRIORITY: 'REMOVE_PRIORITY',
    ADD_PRIORITY: 'ADD_PRIORITY',
    ALL_PRIROTY_STATUS: "ALL_PRIROTY_STATUS",
    REMOVE_NEW_CALENDER: 'REMOVE_NEW_CALENDER',
    ADD_NEW_CALENDER: 'ADD_NEW_CALENDER',
    UPDATE_ALL_NEW_CALENDER_EVENTS: 'UPDATE_ALL_NEW_CALENDER_EVENTS',
    SHOW_MODEL: 'SHOW_MODEL',
    UPDATE_ALL_CALENDER_EVENTS: 'UPDATE_ALL_CALENDER_EVENTS',
    FETCH_ALL_NEW_CALENDER_EVENTS: 'FETCH_ALL_NEW_CALENDER_EVENTS',
    ALL_CALENDER_EVENTS: 'ALL_CALENDER_EVENTS'
});
